-- Tabelas de auditoria Envers para os testes com H2.
--
-- O profile "test" usa ddl-auto=create-drop, que cria apenas as tabelas mapeadas por
-- entidades; as tabelas *_aud e revinfo sao geradas pelo Envers em runtime e nao entram
-- nesse schema. Sem elas, qualquer escrita em entidade @Audited falha.
--
-- Em PostgreSQL essas tabelas vem da migration V4__create_audit_tables.sql. Este script e
-- o equivalente para H2, escrito com "if not exists" para poder ser aplicado por @Sql em
-- varios testes sobre o mesmo banco em memoria.

CREATE TABLE IF NOT EXISTS revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS gestantes_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    version BIGINT,
    nome VARCHAR(160),
    data_nascimento DATE,
    telefone VARCHAR(30),
    email VARCHAR(160),
    data_ultima_menstruacao DATE,
    data_provavel_parto DATE,
    observacoes CLOB,
    data_cadastro TIMESTAMP,
    data_atualizacao TIMESTAMP,
    PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS procedimentos_prenatal_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    version BIGINT,
    nome VARCHAR(180),
    descricao CLOB,
    tipo VARCHAR(40),
    trimestre_recomendado VARCHAR(20),
    semana_inicial_recomendada INTEGER,
    semana_final_recomendada INTEGER,
    obrigatorio BOOLEAN,
    ativo BOOLEAN,
    PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS itens_checklist_gestante_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    version BIGINT,
    gestante_id BIGINT,
    procedimento_id BIGINT,
    status VARCHAR(30),
    data_prevista DATE,
    data_realizacao DATE,
    observacao CLOB,
    data_criacao TIMESTAMP,
    data_atualizacao TIMESTAMP,
    PRIMARY KEY (id, rev)
);

CREATE TABLE IF NOT EXISTS consultas_prenatal_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    version BIGINT,
    gestante_id BIGINT,
    data_consulta DATE,
    semana_gestacional INTEGER,
    peso NUMERIC(5, 2),
    pressao_arterial VARCHAR(20),
    observacoes CLOB,
    data_registro TIMESTAMP,
    PRIMARY KEY (id, rev)
);
