package estevezalvarez.GestarAfeto.auditoria;

import estevezalvarez.GestarAfeto.auditoria.service.AuditoriaService;
import estevezalvarez.GestarAfeto.gestante.dto.CriarGestanteRequest;
import estevezalvarez.GestarAfeto.gestante.service.GestanteService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;

import java.time.LocalDate;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest
@ActiveProfiles("test")
class AuditoriaIntegrationTest {

    @Autowired
    private GestanteService gestanteService;

    @Autowired
    private AuditoriaService auditoriaService;

    @Test
    @Sql(statements = {
        "create table if not exists revinfo (rev integer generated by default as identity primary key, revtstmp bigint not null)",
        "create table if not exists gestantes_aud (id bigint not null, rev integer not null, revtype smallint, version bigint, nome varchar(160), data_nascimento date, telefone varchar(30), email varchar(160), data_ultima_menstruacao date, data_provavel_parto date, observacoes clob, data_cadastro timestamp, data_atualizacao timestamp, primary key (id, rev))"
    })
    void registraEConsultaRevisoesDeGestante() {
        var criada = gestanteService.cadastrar(new CriarGestanteRequest(
            "Luciana",
            null,
            null,
            "luciana@example.com",
            null,
            LocalDate.now().plusMonths(3),
            "Primeiro cadastro"
        ));
        gestanteService.atualizar(criada.id(), new CriarGestanteRequest(
            "Luciana Pereira",
            null,
            null,
            "luciana@example.com",
            null,
            LocalDate.now().plusMonths(3),
            "Cadastro revisado"
        ));

        var revisoes = auditoriaService.historico("gestante", criada.id());

        assertTrue(revisoes.size() >= 2);
        assertEquals("ADD", revisoes.getFirst().tipoAlteracao());
        assertTrue(revisoes.getLast().dados().get("nome").toString().contains("Pereira"));
    }
}
