CREATE TABLE revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstmp BIGINT NOT NULL
);

CREATE TABLE gestantes_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    version BIGINT,
    nome VARCHAR(160),
    data_nascimento DATE,
    telefone VARCHAR(30),
    email VARCHAR(160),
    data_ultima_menstruacao DATE,
    data_provavel_parto DATE,
    observacoes TEXT,
    data_cadastro TIMESTAMP,
    data_atualizacao TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_gestantes_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

CREATE TABLE procedimentos_prenatal_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    version BIGINT,
    nome VARCHAR(180),
    descricao TEXT,
    tipo VARCHAR(40),
    trimestre_recomendado VARCHAR(20),
    semana_inicial_recomendada INTEGER,
    semana_final_recomendada INTEGER,
    obrigatorio BOOLEAN,
    ativo BOOLEAN,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_procedimentos_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

CREATE TABLE itens_checklist_gestante_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    version BIGINT,
    gestante_id BIGINT,
    procedimento_id BIGINT,
    status VARCHAR(30),
    data_prevista DATE,
    data_realizacao DATE,
    observacao TEXT,
    data_criacao TIMESTAMP,
    data_atualizacao TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_checklist_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

CREATE TABLE consultas_prenatal_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT,
    version BIGINT,
    gestante_id BIGINT,
    data_consulta DATE,
    semana_gestacional INTEGER,
    peso NUMERIC(5, 2),
    pressao_arterial VARCHAR(20),
    observacoes TEXT,
    data_registro TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_consultas_aud_rev FOREIGN KEY (rev) REFERENCES revinfo(rev)
);

CREATE INDEX idx_gestantes_aud_id ON gestantes_aud (id);
CREATE INDEX idx_checklist_aud_id ON itens_checklist_gestante_aud (id);
CREATE INDEX idx_consultas_aud_id ON consultas_prenatal_aud (id);
